### ISSUE TITLE
Cant install Plugin 

### ISSUE THREAD

**Issue by fahcsim** [ThePicklenat0r/hassio-ngrok#11]
After installing Hassio again I am unable to install the plugin. I had been using version 1.02 successfully before. Below are the logs from hassio:

20-01-18 00:18:23 INFO (SyncWorker_18) [hassio.docker.interface] Pull image thepicklenat0r/armv7-hassio-ngrok tag v2.1.0.
20-01-18 00:18:24 ERROR (SyncWorker_18) [hassio.docker.interface] Can't install thepicklenat0r/armv7-hassio-ngrok:v2.1.0 -> 404 Client Error: Not Found ("manifest for thepicklenat0r/armv7-hassio-ngrok:v2.1.0 not found").
20-01-18 00:19:21 INFO (SyncWorker_16) [hassio.docker.interface] Pull image thepicklenat0r/armv7-hassio-ngrok tag v2.1.0.
20-01-18 00:19:23 ERROR (SyncWorker_16) [hassio.docker.interface] Can't install thepicklenat0r/armv7-hassio-ngrok:v2.1.0 -> 404 Client Error: Not Found ("manifest for thepicklenat0r/armv7-hassio-ngrok:v2.1.0 not found").

**Comment by ThePicklenat0r** [comment]
Hi fahcsim,

Thanks for pointing this out, it should be fixed in v2.1.1 which I'm about to release.

Also, note that I made some major changes a while back to the how to set the tunnel configs and it is now completely contained inside the addon's config section, I didn't document them very well at the time, but everything in the readme should be up to date now.

**Comment by fahcsim** [comment]
Thanks for the reply and thanks for making this! Keep up the god work, cheers!
